RAPT21/bro3-tools

bro3_Auto_Bilder/bro3_Auto_Bilder.user.js

close #6 
兵士作成中画面のレイアウトが変更されたことにより、作成中兵士数を正常に取得できなくなっていた。
作成中兵士の欄にキャンセルボタンがついたことにより、キャンセルボタンから情報を取得するよう修正。
なお、キャンセルボタンから取得した作成時間と既存の画面から取得した時間に数秒の差異があるが、本PR作成においては既存踏襲を優先することとしている。
兵士作成中の表示

現在作成中の兵士数が正しく表示されなくなっていた問題を修正 #6

---

bro3_beyond/bro3_beyond.user.js

2401x2401 MAP にて、(-900,-900)-(900,900) の範囲外を探索できない。
入力値バリデーションにて、1801x1801 MAP までしか対応していなかった。
入力値バリデーションにて、2401x2401 MAP まで許容するよう修正。
- 資源パネル探索
- NPC座標・NPC隣接同盟探索

[Beyond] 資源・NPC探索機能について2401MAP対応

---

bro3_beyond/bro3_beyond.user.js

- enhanced
- 「ランキングへのリンクを追加」で寄付、破壊、破砕スコア、南蛮撃退も対象とするように
- メニューへ「統計＞資源」を追加
- changes
- メニューの「統計＞全体」を、「統計＞状況」へ変更（運営の項目名に合わせるよう修正）
- fix
- 「ランキングへのリンクを追加」で同盟、DPのリンクが利いていなかった問題を修正

10/22 付けの仕様変更対応

---

bro3_beyond/bro3_beyond.user.js

- enhanced
- 「ランキングへのリンクを追加」で君主官位も対象とするように
- 「デッキ：現在の所持枚数をファイルの上部へ移動する」オプションを追加
- これを有効にすることで、一括ラベルセットボタンも元の位置（ファイルの上部）に表示されます。

「デッキ：現在の所持枚数をファイルの上部へ移動する」オプションを追加ほか

---

bro3_beyond/bro3_beyond.user.js

- enhanced
- 「報告書＞自動鹵獲結果のリンクを消す」オプションを追加
- 統計＞資源と同じなのと「全てを既読にする」ボタンと押し間違える対策
- fix
- 「報告書＞討伐・攻撃ログのTSV出力機能の追加」のチェックを外してもボタンが消えないバグを修正

報告書のオプション追加とバグ修正

---

bro3_auto_daily_quest/bro3_auto_daily_quest.user.js

デュエルのURLが変更されており、旧URLは 404 NOT FOUND になっていたのが原因。
また、「運営書簡を既読にする」の動作がバギーだったが、
そもそもログインボーナス書簡がうざかったのが存在価値だったため、
ログインボーナス書簡廃止に伴い、「運営書簡を既読にする」オプションも廃止。

12/4 のメンテ以降、自動デュエルが動作しなくなっていた問題を修正

---

README.md
bro3_busyodas/bro3_busyodas.user.js

ブショーダスライトで「ブショーダスを10回引く」ボタンを押したとき、
不要なカードについて、自動で削除チェックを入れるツール。
単純な機能ながら、BP 消化時に仁君カードなどを誤って削除しないようにする。
※今のところ1枚引きには未対応。
※引くのは手動。削除も手動。あくまでチェックを入れるだけ。

ブショーダスライト補助ツール

---

bro3_donate_window/bro3_donate_window.user.js

- https 対応
- 同盟画面、プロフィール画面の仕様変更に伴い、新規サーバーや君主名を変更したときなどに寄付ができなくなっていた問題を修正
- 原因: 保存された君主名がない場合か、同盟画面に表示される君主名と保存された君主名が異なる場合、プロフィール画面から君主名を取得していましたが、プロフィール画面の仕様変更に伴い、君主名が取得できず無限ループしていました。
- 対応: 同盟画面の仕様変更に伴い、君主名は不要になったので君主名の処理を外しました。

[donate window] 寄付ができない場合がある問題を修正

---

bro3_territory_info/bro3_territory_info.user.js

- https 対応
- 戦力表記が変更された対応
- `★` → `★[1]` のように変更されたが、CSV 出力時は元の `★` で出力するように
- NPC領地は空き地のためリストアップしないように
一応、地形1.0未対応サーバー、地形1.0対応サーバー、でも動作することを確認。

[territory info] 51x51MAPで従来のフォーマットで出力できるように

---

README.md
bro3_auto_capture_setting/bro3_auto_capture_setting.user.js

自動鹵獲出兵先設定を簡単に編集できるようにします。
土地画面（右下に簡易出兵先、自動鹵獲、自動出兵のメニューがある画面）で、「自動鹵獲」をクリックすると設定画面を開けます。
再度「自動鹵獲」をクリックすると設定画面を閉じます。
「本拠地デッキに登録する」、「拠点デッキに登録する」をクリックでメイン画面更新なしで登録できます。
設定画面下部には現在の設定内容を表示します。ここから個別に削除できます。
現在表示している座標が登録済の場合、背景色がピンク色になります。
本拠地デッキ、拠点デッキ、それぞれについて10件登録済の場合はいずれか削除してから登録してください。
鹵獲先リストのExport/Importが可能です。
たとえば本拠地デッキに登録した座標と同じ内容で拠点デッキに登録したい場合は、
本拠地デッキ側にExportされた内容を拠点デッキ側にコピペして、「Import開始」をクリックしてください。
ImportフォーマットはJSON形式だけでなく、(x,y)形式で改行区切りにしたリストも利用できます。
例）
```
(100,100)
(200,200)
(300,300)
```
**備考**
鹵獲先の有効化や優先順位はインポートできないため、自動鹵獲出兵先設定画面で編集してください

[auto capture setting] ブラウザ三国志 自動鹵獲設定補助ツール

---

bro3_beyond/bro3_beyond.user.js

- オプションに「共通：地形1.0」を追加
- 本PR作成時点で未導入のサーバーではデフォルト Off です。それ以外は On になります。
- メニューの一部を地形1.0対応
- 全体地図、同盟、軍議所を変更
- ※軍議所→城壁塔の項目については地形1.0未対応マップでも表示されます
- 地形1.0マップで「Profile：NPC隣接同盟探索」が動作するよう暫定対処
- NPC砦の所有同盟名が取得できなくなったため、代わりに所有盟主名を取得するように

[beyond] 地形1.0 対応（一部）

---

bro3_beyond/bro3_beyond.user.js

- 1.09.29 での変更 d7e2d14ecbea91af2228af2d2e974a7669e40d6f が原因で動作しなくなっていた機能を修正
- 同盟ログ検索
- 一括ラベル設定
- #52 
- w7, w20 の地形1.0対応設定初期値を `true` へ変更

[beyond] 同盟ログ検索、一括ラベル設定が動作しなくなっていた不具合を修正

---

bro3_beyond/bro3_beyond.user.js

Closes #52
- 「倉庫からファイルに移動する画面へ一括ラベル機能を追加」を追加
- 「Profile：資源パネル探索」が動作するよう修正
- 「Profile：NPC座標探索」が動作するよう修正
[bro3_beyond.user.js](https://github.com/RAPT21/bro3-tools/blob/master/bro3_beyond/bro3_beyond.user.js)

[beyond] 地形1.0 対応（領地探索系）

---

bro3_Auto_Bilder/bro3_Auto_Bilder.user.js

- 城壁塔対応鯖で、NPC砦持ちの盟主のとき、プロフィール画面を開いても要塞、城壁塔の拠点情報が取得できなくなっていた対策
- プリセットの設定値を調整

[auto bilder] 城壁塔対応鯖で、NPC砦持ちの盟主のとき、プロフィール画面を開いても要塞、城壁塔の拠点情報が取得できなくなっていた対策

---

bro3_beyond/bro3_beyond.user.js

- スキル連続レベルアップ時、「副将の明鏡」系スキルがLVUP対象外になっていたのを、LVUPできるよう修正
- 従来通り、この画面で副将としてセットしているカードのスキルはLVUP対象外
[bro3_beyond.user.js](https://github.com/RAPT21/bro3-tools/blob/master/bro3_beyond/bro3_beyond.user.js)

[beyond] スキル連続レベルアップ時、主将スキルとしての副将の明鏡スキルもLVUPできるように

---

bro3_beyond/bro3_beyond.user.js

１．同盟内ランキングで、矢印ボタンでソートを行った場合、数値でソートできない不具合を修正
２．内政官を一度に下げるボタンのサイズを調整し、デッキ内でのカード表示がずれる問題を修正
３．gyazoのファイル形式がpngとjpgに(多分)変更になったことに伴い、書簡内のgyzaoの展開が行われなくなった不具合を修正、ただし、gif(主にgif動画)には未対応

同盟内ランキングソート不具合、内政官を下げるボタンのサイズ、書簡内のgyazoの展開の不具合修正

---

bro3_send_friendly_army/bro3_send_friendly_army.user.js

- 地形対応サーバーで基本鋭兵の概念が導入されたため、基本鋭兵が自動造兵できなくなっていたのを修正
- 大剣兵はまず使わないためコメントアウト
- コメントアウトを外せばほかの兵科同様に利用可能です。
[bro3_send_friendly_army.user.js](https://github.com/RAPT21/bro3-tools/blob/master/bro3_send_friendly_army/bro3_send_friendly_army.user.js)

[send_friendly_army] 地形対応サーバーで基本鋭兵が自動造兵できなくなっていたのを修正

---

bro3_quick_make_soldier/bro3_quick_make_soldier.user.js

- 地形対応サーバーで基本鋭兵の概念が導入されたため、基本鋭兵が自動造兵できなくなっていたのを修正
- 大剣兵はまず使わないためコメントアウト
- コメントアウトを外せばほかの兵科同様に利用可能です。
[bro3_quick_make_soldier.user.js](https://github.com/RAPT21/bro3-tools/blob/master/bro3_quick_make_soldier/bro3_quick_make_soldier.user.js)

[quick_make_soldier] 地形対応サーバーで基本鋭兵が自動造兵できなくなっていたのを修正

---

bro3_initial_quest_helper/bro3_initial_quest_helper.user.js

- 総人口と撃破スコアが正しく取得できなくなっていたのを修正
- 地形2.0サーバーで君主名が取得できなくなったのを修正
[bro3_initial_quest_helper.user.js](https://github.com/RAPT21/bro3-tools/blob/master/bro3_initial_quest_helper/bro3_initial_quest_helper.user.js)

[initial_quest_helper] 総人口と撃破スコアが正しく取得できなくなっていたのを修正

---

bro3_donate_window/bro3_donate_window.user.js

- 地形2.0対応
- 同盟画面に役割列が追加されたことで既寄付額が取得できなくなっていたのを修正
[bro3_donate_window.user.js](https://github.com/RAPT21/bro3-tools/blob/master/bro3_donate_window/bro3_donate_window.user.js)

[donate_window] 地形2.0対応。同盟画面に役割列が追加されたことで既寄付額が取得できなくなっていたのを修正

---

README.md
bro3_npc_expedition/bro3_npc_expedition.user.js

北伐出陣画面で予備兵画像をクリックするとまとめて引率兵を切り替えます。
1. 予備兵画像をマウスでホバーするとマウスカーソルが手の指アイコンに切り替わります。
1. この状態で予備兵画像をクリックすると、引率兵をまとめて切り替え、かつ自動補充にチェックを入れます。
- まれにうまく反映されない場合がありますが、そのときはもう一度クリックしてみてください。
[bro3_npc_expedition.user.js](https://github.com/RAPT21/bro3-tools/blob/master/bro3_npc_expedition/bro3_npc_expedition.user.js)

[npc_expedition] 北伐予備兵切り替えツールを追加

---

README.md
bro3_use_multi_items/bro3_use_multi_items.user.js

宝物庫から水鏡などを移動するとき、通常は１枚ずつしか使用できません。ブラウザーによってはクリック連打で複数枚移すこともできますが、面倒です。
これを自動でまとめて移動させます。
※1枚の移動であっても運営のUIよりも高速です。
ファイルの空き容量をチェックとかはしていないので、あらかじめご自身で確認しておいてください。
大量の水鏡を使いたかったり、倉庫に移動させるのに便利と思います。
[bro3_use_multi_items.user.js](https://github.com/RAPT21/bro3-tools/blob/master/bro3_use_multi_items/bro3_use_multi_items.user.js)

宝物庫まとめて移動ツールを追加

---

bro3_beyond/bro3_beyond.user.js

- デッキ：内政スキル使用リンクの追加（回復：赤/緑、内政：青）で、赤字リンク（呼集系スキルなど）が指定拠点以外で発動しないよう修正
- メニューに南蛮襲来、北伐出陣（EX出現No）の項目などを追加
[bro3_beyond.user.js](https://github.com/RAPT21/bro3-tools/blob/master/bro3_beyond/bro3_beyond.user.js)

[beyond] 内政スキル利用リンクで呼集など指定拠点で発動しないことがある不具合を修正、ほか

---

bro3_help_army_report/bro3_help_army_report.user.js

- 援軍チェック時、南蛮衛兵も検出していたため、援軍君主とし誤カウントしていたので、南蛮衛兵は除外するように
- 援軍部隊数のカウントがずれていたのを修正(1つ多かった)
#91 
[bro3_help_army_report.user.js](https://github.com/RAPT21/bro3-tools/blob/master/bro3_help_army_report/bro3_help_army_report.user.js)

[help_army_report] 南蛮援軍確認ツールで南蛮衛兵を検出しないように
